repo: "header-icons"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Merriweather"]', 'The Google Font, `Merriweather` is missing']
      - 'header'
      - 'header h1'
      - 'header img'
      - 'header nav'
      - 'header ul'
      - 'header a'
      - 'img[src*="grain-left.svg"]'
      - 'img[src*="grain-right.svg"]'
    search:
      - "Grains"
      - "Home"
      - "Cereals"
      - "Legumes"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ["html", "box-sizing", "border-box"]
      - ['*', 'box-sizing', 'inherit']
      - ["body", "margin", 0]
    search:
      - "#d05c2e"
      - "#a63f38"
      - "float: left"
      - "float: right"

screenshots:
  - path: "index.html"
    sizes: [320, 650]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('nav a');
        let oldBg = css(link).backgroundColor;

        hover('nav a', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the navigaiton links don’t change when hovered')
          pass();
        });
